database:
  uri: "mongodb://localhost/minecraft"

messages:
  next-page-name: "&aNext Page (%page%)"
  previous-page-name: "&aPrevious Page (%page%)"
  category-entry-name: "&a%category%"
  category-entry-lore: ""
  buy-item-name: "&aBuy"
  buy-item-lore: ""
  sell-item-name: "&aSell"
  sell-item-lore: ""
  category-menu-title: "Categories %type% - %page%"
  back-name: "&aGo Back"