name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  prismatrade:
    aliases: ["pt"]
    description: "Admin Command for PrismaTrade"
  trade:
    aliases: ["shop", "ah", "auction"]
    description: "Open the trading menu"
  buy:
    description: "Buy items from the shop"
  sell:
    description: "Sell items from your hand"