name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
commands:
  trade:
    aliases: ["shop", "ah", "auction"]
    description: "Open the trading menu."